### PR TITLE
Added basic SeaMonkey support

### PR DESCRIPTION
**Pull request by VeridianDynamics**
Pretty much everything works fine, only the number of unread items next to the Brief icon is missing. I believe it's due to the fact that SeaMonkey does not support CustomizableUI yet, but SeaMonkey developers are working on that.

Why did I do this? I'm abandoning Firefox in favour of SeaMonkey, and I'm taking all the add-ons with me! :-)

### CODE REVIEW

**Comment by tanriol** [comment]
Are there any additional difficulties we will need to be aware of if this is accepted?

As I understand, the current SeaMonkey release uses the same Gecko version as the current Firefox release. Does it introduce any additional limitations on addons?

Also, please note that neither me nor @anestorak use SeaMonkey, so it will probably be almost untested. However, if you're ready to support this port, I have no objections.

@ancestorak, your opinion?

**Comment by VeridianDynamics** [comment]
Yes, I know I'll have to support this myself, but that's a small price to pay for using SeaMonkey (very much like Firefox, but without all the terrible UX decisions since FF 3). In fact, Brief is so important to my web browsing that I will have no choice but to maintain the compatibility.

It shouldn't cause any problems or introduce limitations, but I'm quite new to extension development so take it with a grain of salt. I believe the worst case scenario is that it will stop working on SM and I'll have to fix it.

**Comment by nohamelin** [comment]
Currently there is a gap in the number versions between a Gecko release and the correspondent SeaMonkey release that includes it. The real compatibility info in the patch should be:

```
<minVersion>2.26.*</minVersion>
<maxVersion>2.34.*</maxVersion>
```

**Comment by VeridianDynamics** [comment]
@nohamelin: Good point, versions changed. Where can I find the information about which version of Firefox corresponds to which versions of SeaMonkey?

**Comment by nohamelin** [comment]
[SeaMonkey releases history | Wikipedia] (https://en.wikipedia.org/wiki/SeaMonkey#Release_history)

**Comment by VeridianDynamics** [comment]
Could someone merge this to master or are there some issues to be resolved?

**Comment by tanriol** [comment]
@VeridianDynamics, are you still interested in SeaMonkey support in Brief?

**Comment by VeridianDynamics** [comment]
Hi,
apologies for replying so late, of course I do. I've been actively using 
the build I created a year ago, but it would be nice to have the new 
features and bugfixes too.

Thanks!

**Comment by tanriol** [comment]
At the moment this PR is out of date and Brief is in the middle of migration off XUL. You can choose to update it for Brief 2.3 (e10s-ready, but still a XUL add-on) or wait for the next changes.

**Comment by tanriol** [comment]
At the current point in the timeline I'm closing this PR. Unfortunately, I don't have enough time to keep multiple Brief codebases going, thus the only one I'm working at is the hybrid -> WebExtensions one. I'll be happy to add the required support, if any, when SeaMonkey supports WebExtensions (at least partially).

**Pull request closed without merging**
